# Finger smoothing
FINGER_EMA_ALPHA = 0.45

# TUNABLES
PLACEMENT_COOLDOWN = 0.1
PLACEMENT_MIN_MOVE = 4.0
PINCH_STABLE_TIME = 0.06
MIN_SCREEN_BLOCK_SIZE = 2


# Block visuals
BLOCK_VISUAL_SCALE = 1.0
BLOCK_VISUAL_SCALE_ALLOW_OVERLAP = False
